#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/lkrapf/helixtest.git"

strains:
  - name: default
    code: https://github.com/lkrapf/helixtest.git#master
    content: https://github.com/lkrapf/helixtest.git#master
    static: https://github.com/lkrapf/helixtest.git/htdocs#master
    package: lkrapf/50bc8179fbb6eec90cf9f574d541af6268aeda9b
